// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PAPI_Libs.Data;

#nullable disable

namespace PAPI_Libs.Migrations
{
    [DbContext(typeof(PAPI_LibContext))]
    partial class PAPI_LibContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("PAPI_Libs.Models.PAPI_Lib", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiNameOne")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiNameTwo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiUrlOne")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiUrlTwo")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedString")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalQuote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalQuoteAuthorOrSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PAPI_LibTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PAPI_Libs");
                });

            modelBuilder.Entity("PAPI_Libs.Models.PAPI_LibTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiNameOne")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiNameTwo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiUrlOne")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiUrlTwo")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalQuote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalQuoteAuthorOrSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PAPI_LibTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
